-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 22:03:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBventas` DEFAULT CHARACTER SET utf8 ;
USE `DBventas` ;

-- -----------------------------------------------------
-- Table `DBventas`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `dni` VARCHAR(8) NULL,
  `edad` VARCHAR(45) NULL,
  `ruc` VARCHAR(11) NULL,
  `direccion` VARCHAR(50) NULL,
  `fecha_nacimiento` DATE NULL,
  `correo_electronico` VARCHAR(50) NULL,
  `telefono` VARCHAR(9) NULL,
  `id_cliente_independiente` INT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_persona_cliente_independiente_idx` (`id_cliente_independiente` ASC),
  CONSTRAINT `fk_persona_cliente_independiente`
    FOREIGN KEY (`id_cliente_independiente`)
    REFERENCES `DBventas`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`cliente_c`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`cliente_c` (
  `id_cliente_c` INT NOT NULL AUTO_INCREMENT,
  `fotografia` VARCHAR(100) NOT NULL,
  `tipo_contrato` VARCHAR(20) NOT NULL,
  `saldo_inicial` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `distrito` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cliente_c`),
  INDEX `fk_cliente_c_persona_idx` (`id_persona` ASC),
  CONSTRAINT `fk_cliente_c_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `DBventas`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`estado_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`estado_cuenta` (
  `id_estado_cuenta` INT NOT NULL AUTO_INCREMENT,
  `deuda_total` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  `saldo_final` INT NOT NULL,
  `id_cliente_c` INT NOT NULL,
  PRIMARY KEY (`id_estado_cuenta`),
  INDEX `fk_estado_cuenta_cliente_c_idx` (`id_cliente_c` ASC),
  CONSTRAINT `fk_estado_cuenta_cliente_c`
    FOREIGN KEY (`id_cliente_c`)
    REFERENCES `DBventas`.`cliente_c` (`id_cliente_c`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `tipo_empleado` VARCHAR(20) NOT NULL,
  `salario` INT NOT NULL,
  `fecha_contrato` DATE NOT NULL,
  `dias_laborales` VARCHAR(20) NOT NULL,
  `fecha_fin_contrato` DATE NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleado_persona_idx` (`id_persona` ASC),
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `DBventas`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `valor_total` INT NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  `id_meza` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_persona_idx` (`id_persona` ASC),
  INDEX `fk_pedido_empleado_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_pedido_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `DBventas`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `DBventas`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`grupo_platillos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`grupo_platillos` (
  `id_grupo_platillos` INT NOT NULL AUTO_INCREMENT,
  `clasificacion` VARCHAR(40) NOT NULL,
  `grupo_platilloscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo_platillos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`area` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `tipo_area` VARCHAR(30) NOT NULL,
  `areacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`platillo` (
  `id_platillo` INT NOT NULL AUTO_INCREMENT,
  `nombre_platillo` VARCHAR(50) NOT NULL,
  `precio_platillo` INT NOT NULL,
  `medida` INT NOT NULL,
  `id_area` INT NOT NULL,
  `id_grupo_platillos` INT NOT NULL,
  PRIMARY KEY (`id_platillo`),
  INDEX `fk_platillo_grupo_platillos_idx` (`id_grupo_platillos` ASC),
  INDEX `fk_platillo_area_idx` (`id_area` ASC),
  CONSTRAINT `fk_platillo_grupo_platillos`
    FOREIGN KEY (`id_grupo_platillos`)
    REFERENCES `DBventas`.`grupo_platillos` (`id_grupo_platillos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_platillo_area`
    FOREIGN KEY (`id_area`)
    REFERENCES `DBventas`.`area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`pedido_platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`pedido_platillo` (
  `id_pedido` INT NOT NULL,
  `id_platillo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` INT NOT NULL,
  INDEX `fk_pedido_platillo_pedido_idx` (`id_pedido` ASC),
  INDEX `fk_pedido_platillo_platillo_idx` (`id_platillo` ASC),
  CONSTRAINT `fk_pedido_platillo_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `DBventas`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_platillo_platillo`
    FOREIGN KEY (`id_platillo`)
    REFERENCES `DBventas`.`platillo` (`id_platillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`mesa` (
  `id_mesa` INT NOT NULL AUTO_INCREMENT,
  `numero_mesa` VARCHAR(2) NOT NULL,
  `capacidad_mesa` VARCHAR(2) NOT NULL,
  `ubicacion_mesa` VARCHAR(40) NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_mesa`),
  INDEX `fk_mesa_empleado_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_mesa_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `DBventas`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBventas`.`comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBventas`.`comprobante` (
  `id_comprobante` INT NOT NULL,
  `tipo_comprobante` VARCHAR(10) NOT NULL,
  `numero_comprobante` VARCHAR(20) NOT NULL,
  `igv` INT NOT NULL,
  `fecha_comprobante` DATE NOT NULL,
  `id_cliente_independiente` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_comprobante`),
  INDEX `fk_comprobante_cliente_independiente_idx` (`id_cliente_independiente` ASC),
  INDEX `fk_comprobante_pedido_idx` (`id_pedido` ASC),
  CONSTRAINT `fk_comprobante_cliente_independiente`
    FOREIGN KEY (`id_cliente_independiente`)
    REFERENCES `DBventas`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprobante_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `DBventas`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
